image: Visual Studio 2017

install:
- ps: [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
- ps: $msiPath = "$env:TEMP\PowerShell-Core.msi"
- ps: (New-Object Net.WebClient).DownloadFile('https://github.com/PowerShell/PowerShell/releases/download/v6.2.3/PowerShell-6.2.3-win-x64.msi', $msiPath)
- ps: cmd /c start /wait msiexec /i $msiPath /quiet
- ps: del $msiPath
- ps: Add-SessionPath "$env:ProgramFiles\PowerShell\6"
- ps: pwsh --version

build_script:

# copy module contents
- ps: New-Item AppVeyorBYOC -Type Directory | Out-Null
- ps: Copy-Item -Path appveyor-byoc-psm\* -Destination AppVeyorBYOC
- ps: New-Item AppVeyorBYOC\scripts -Type Directory | Out-Null
- ps: Copy-Item -Path scripts\* -Destination AppVeyorBYOC\scripts -Recurse
- ps: New-Item AppVeyorBYOC\hyper-v -Type Directory | Out-Null
- ps: Copy-Item -Path hyper-v\* -Destination AppVeyorBYOC\hyper-v -Recurse
- ps: New-Item AppVeyorBYOC\http -Type Directory | Out-Null
- ps: Copy-Item -Path http\* -Destination AppVeyorBYOC\http -Recurse
- ps: Copy-Item -Path AppVeyorBYOC-Common.ps1 -Destination AppVeyorBYOC
- ps: Copy-Item -Path Connect-*.ps1 -Destination AppVeyorBYOC
- ps: Copy-Item -Path *.json -Destination AppVeyorBYOC

# publish module
- ps: $ModuleVersion = if ($env:APPVEYOR_REPO_BRANCH -eq 'master') {$env:APPVEYOR_BUILD_VERSION} else {"$env:APPVEYOR_BUILD_VERSION-alpha"}
- ps: (Get-Content AppVeyorBYOC\AppVeyorBYOC.psd1).replace("ModuleVersion = '1.0.0'", "ModuleVersion = '$ModuleVersion'") | Set-Content AppVeyorBYOC\AppVeyorBYOC.psd1
- ps: Publish-Module -Path $env:APPVEYOR_BUILD_FOLDER\AppVeyorBYOC -NuGetApiKey $env:psg_api_key

test: off